### PR TITLE
Extract deprecated oclcs

### LINKED ISSUE #404: Add OCLC ID cross-reference
Adding 035z and 019a to the identifiers search will allow people to search OCLC # cross-references. These are deprecated identifiers, often from merges, which may still be the identifier that the person searching has on-hand. However, 019s can contain some really bad historical data, so we will need to run a regex and only index ones in which the field _**only contains numbers** and those numbers can be 3-15 numbers, anything longer than that is probably a different number_.

Also, there can be overlap between 035zs and 019as, so we will probably need to unique it if we're not already?

## WDDLL

- [ ] Searching for a deprecated OCLC identifier (035z or 019a) in the identifiers advanced search field returns the appropriate item

(they'll also be in keyword search, but that'll be handled by https://github.com/psu-libraries/psulib_traject/issues/181 )

Sample data:

### 035z

- catkey `22621759`:  `265439141`, `660069515`
- catkey `432730`: `10194249`, `10265210`, `14780806`, `20694489`, `23322680`, `33075119`, `41574240`
- catkey: `5973408`: `52944261`, `74270573`, `156823507`, `191928018`, `449859090`

### 019a

- catkey: `18158600`: `982166495`, `1004793185`, `1011112561`, `1066476482`, `1066483523` (note, these are all in one field, repeating subfield a -- there's another 019 that's... MARS)
- catkey: `426356`: `258994`, `9795777`, `10601074`, `56416291`, `212324284`, `221616458`, `221874331`, `222647407`, `228671499`, `231051888`, `232576977`, `320803143`, `663056427`, `684742283`, `700287900`, `748679626`, `752959506`, `769265324`, `770876040`, `774895605`, `775455212`, `780713141`, `796999334`, `799150396`, `827454568`, `829063228`, `839666159`, `841354703`, `864664601`, `868202318`, `875650663`, `877408023`, `880952450`, `882607987`, `884429176`, `890961781`, `894653084`, `894770863`, `895365169`, `897425541`, `900318121`, `900527964`, `950903106`, `958368527`, `1061067521`, `1065035760`, `1116048388`, `1160098034`, `1179683711` `1223547243`, `1223922992`, `1238121421`
- catkey: `5973408`: `52944261`, `74270573`, `156823507`, `191928018`, `449859090`

### PR DESCRIPTION
**Pull request by ajkiessl**
Some of this code could potentially be refactored and abstracted into its own Processor class.  I didn't do this though since there were some shared methods in the Macros module.  I felt this needed a test too. The one I added seems a bit weird and there may be a better way of doing it, but it works.

closes #404

### CODE REVIEW

**Comment by nicktiberi** [comment]
Overall this looks pretty clean to me, but I know what you mean about the potential refactor.

It looks like the only shared method is just `regex_split`, right? I guess if you wanted to, you could put it in a catchall `Utils` class as a static method and call it as `Utils.regex_split(str, regex)`. Then you could move the OCLC stuff into its own processor.

**Comment by ajkiessl** [comment]
@nicktiberi  Yeah it's that `regex_split`.  Your solution sounds good to me.

**Comment by banukutlu** [comment]
This PR looks good to me overall, I like Nick's refactor suggestion if you'd like to go with that refactor sounds good to me 👌🏻

**Review by banukutlu — DISMISSED** [review]
lgtm 👍🏻

**Review by banukutlu — APPROVED** [review]
nice 👌🏻  thanks!

**Pull request merged**
