### PR TITLE
upgrading to JRuby 9.4.2.0

### PR DESCRIPTION
**Pull request by Smullz622**

### CODE REVIEW

**Review by whereismyjetpack — DISMISSED** [review]

**Comment by ajkiessl** [comment]
I noticed there's a change in the travis.yml.  Can we just delete the travis.yml since it is not being used anymore?  Alsp, should we consider bumping the ruby version in the circleci.yml? I haven't been able to fully dig into the circleci setup, but I'm not sure if the defined ruby version in there is the version being used by the tests/linting.

**Review by ajkiessl — CHANGES_REQUESTED** [review]
Yeah, looking at it some more, I think this should be bumped to something in the 3.1.x range:

https://github.com/psu-libraries/psulib_traject/blob/main/.circleci/config.yml#L41

**Comment by whereismyjetpack** [comment]
travis can go. I'm not sure why it's even there!

**Review by whereismyjetpack — APPROVED** [review]

**Review by ajkiessl — APPROVED** [review]
LGTM

**Pull request merged**
